compile:
	GOOS=windows GOARCH=386 go build -o bin/utm_login-windows-386.exe main.go
	GOOS=windows GOARCH=amd64 go build -o bin/utm_login-windows-amd64.exe main.go
	GOOS=windows GOARCH=arm go build -o bin/utm_login-windows-arm.exe main.go
	GOOS=windows GOARCH=arm64 go build -o bin/utm_login-windows-arm64.exe main.go